### ISSUE TITLE
Missing bc_sendemail module?

### ISSUE THREAD

**Issue by bvanvugt** [bitcasa/sendwithus_py2#1]
Hey David, seeing the following error when trying to import the service. 

Is bc_sendemail an internal dependency?

```
>>> from sendwithus_py2 import sendwithus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sendwithus_py2/sendwithus.py", line 22, in <module>
    from bc_sendemail.common.exception import HTTPException, InvalidParam, SendWithUsBatchRejection
ImportError: No module named bc_sendemail.common.exception
```

**Comment by DavidHwu** [comment]
Fixed... thanks Brad!
Moved this from our internal git2 repository... missed this case.
